### ISSUE TITLE
SSMSのURL

### ISSUE THREAD

**Issue by ylearning86** [nakamacchi/AzureCAF.LandingZones.Demo#18]
07.Spoke A (IaaS) イントラ Web アプリのセットアップ/07_01_Web アプリセットアップ.md

において、

https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms

がops端末上とおらず、リダイレクト先の

https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16

をたたくとアクセスできます。

※おそらくFirewall ポリシーでdocs.microsoft.comを解放していないからだと思います。

**Comment by nakamacchi** [comment]
ありがとうございます、修正しておきました。
https://github.com/nakamacchi/AzureCAF.LandingZones.Demo/commit/2d52e499e6e888d945804af58c5bc1331c45fc19
