### ISSUE TITLE
追記：割り当て解除時はエラーが発生します

### ISSUE THREAD

**Issue by ylearning86** [nakamacchi/AzureCAF.LandingZones.Demo#4]
当たり前ですが、、
VMが起動していないと以下のエラーでリネームできない旨を追記していただくとよいかと思います。

Conflict({
  "error": {
    "code": "OperationNotAllowed",
    "message": "The operation requires the VM to be running (or set to run)."
  }
})

05.仮想マシンのコンプライアンス対応/05_01_★ [WindowsOS] ゲストアカウントのリネーム.md

**Comment by nakamacchi** [comment]
ありがとうございます。これ MS メンバー特有かなという気もしており（Azure Policy で強制シャットダウンポリシーが割り当てられているために仮想マシンが止まる）、通常は止まらないので書くのもどうかなと思っていました。一応追記しておきますね。

**Comment by nakamacchi** [comment]
https://github.com/nakamacchi/AzureCAF.LandingZones.Demo/commit/d99af9cdf67449759ad0056814d22be2a740ad78
